# Generated by Django 5.0.6 on 2025-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cafe', 'Cafe'), ('bar', 'Bar'), ('restaurant', 'Restaurant'), ('fastfood', 'Fast Food')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField()),
                ('discount_percent', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
